### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by seanalewine** [InfamousStarFox/OANewsletter#1]
# Overview

The end goal for this project is to implement the new footer (Xtra Xtra) in all of our existing year round templates. We also need to look at converting our existing templates into a `<div>` structure. All templates need to be mobile first with desktop support second.

**Comment by seanalewine** [comment]
# Step 1

The first goal is to implement the Xtra Xtra footer into OA Today.
The footer's default must be to split the address and unsubscribe message into two rows, centered. On Desktop they need to appear within the same row and aligned right/justified. Everything else should scale appropriately 
- [x] Paste the Xtra Xtra footer into OA Today
- [ ] Convert the footer into adaptive `<div>` tags
  Information on how to do this can be found in this article [https://medium.com/cm-engineering/coding-mobile-first-emails-1513ac4673e?source=linkShare-6b34667087ed-1468339260](url)
- [x] Ensure all social links are set to OA standard and not NEXT specific. Snapchat, FB, Twitter, Instagram, Flickr, and Youtube should all be social links

**Comment by seanalewine** [comment]
# Step 2

The next step will be to convert the OA Today template entirely into `<div>` tags. The default width should scale effectively to mobile devices. On desktop devices, the background should become visible and all images should scale upwards. Looking at how this structure was implemented in the Xtra Xtra template may provide some help.
- [ ]  Remove all table related structure from OA Today, and replace them with nested `<div>` tags
- [ ]  Inline **all** CSS and correct any styling issues that may have resulted from the structure conversion
- [ ]  Implement Media Queries into the template, exclusively for the purpose of improving desktop appearance.  Use the Medium article to assist in the conversion process. We do not need to add a two column layout option.

**Comment by seanalewine** [comment]
# Step 3

The last thing we need to do is implement all of these changes into the other templates. For the most part, we should be able to copy and paste the OA Today template into the other templates. Note that some templates do not have certain content options (ex. Lodge Ledger does not need titles or bylines). Ensure you link to the proper header file and set the color options to match the theme of each respective newsletter.
- [ ]  Convert the Lodge Ledger
- [ ] Convert the Trailblazer
- [ ] Convert Live From Dallas (Needs to be rebuilt from OA Today, as some other underlying changes have not been made)
- [ ] Convert The Pulse
- [ ] Create Special Announcement Template???
